services:
  db:
    image: mysql:8.0
    container_name: gudboy_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: gudboy123
      MYSQL_DATABASE: gudboy
    ports:
      - "3306:3306"
    volumes:
      - gudboy_data:/var/lib/mysql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  gudboy_data:
